version: '3.1'
services:  
  db:
    build:
      context: ./db
      dockerfile: dockerfile
    restart: always
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    links:
      - db
  api:
    restart: always
    depends_on: 
      - db
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
       - 4000:4000
    links:
      - db