version: '3.1'
services:  
  db:
    build:
      context: ./db
      dockerfile: dockerfile
    restart: always
    ports:
      - "3308:3306"
    networks:
      - tuckshop_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    links:
      - db
  api:
    restart: on-failure
    depends_on: 
      - db
    build:
      context: ./api
      dockerfile: dockerfile
    links:
      - db
    networks:
      - tuckshop_network
  client:
    restart: always
    depends_on: 
      - api
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - tuckshop_network
networks:
    tuckshop_network:
        driver: bridge